//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Element_Type { get; set; }
        public string Job_Class { get; set; }
        public int ATK { get; set; }
        public int DEF { get; set; }
        public int Mana { get; set; }
        public int HP_Initial { get; set; }
        public int HP_Max { get; set; }
        public bool NPC { get; set; }
    }
}
