//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int MapID { get; set; }
        public int CharacterID { get; set; }
        public string Map_Name { get; set; }
    
        public virtual Character Character { get; set; }
    }
}
